# Generated by Django 4.2 on 2023-04-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petshopapp',
            old_name='id_book',
            new_name='nome',
        ),
    ]
