# Generated by Django 4.2 on 2023-04-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0002_rename_id_book_petshopapp_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petshopapp',
            old_name='nome',
            new_name='id_book',
        ),
    ]
