# Generated by Django 4.2 on 2023-04-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0003_rename_nome_petshopapp_id_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petshopapp',
            old_name='title',
            new_name='name',
        ),
    ]
