# Generated by Django 4.2 on 2023-04-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0004_rename_title_petshopapp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petshopapp',
            name='publishing_company',
        ),
        migrations.RemoveField(
            model_name='petshopapp',
            name='release_year',
        ),
    ]
