# Generated by Django 4.2 on 2023-04-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0005_remove_petshopapp_publishing_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petshopapp',
            old_name='name',
            new_name='nome',
        ),
    ]
