# Generated by Django 4.2 on 2023-04-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0006_rename_name_petshopapp_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petshopapp',
            old_name='author',
            new_name='endereco',
        ),
    ]
