# Generated by Django 4.2 on 2023-04-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0008_rename_state_petshopapp_nome_do_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petshopapp',
            old_name='pages',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='petshopapp',
            name='create_at',
        ),
    ]
