# Generated by Django 4.2 on 2023-04-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0009_rename_pages_petshopapp_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petshopapp',
            name='telefone',
            field=models.CharField(max_length=12),
        ),
    ]
