# Generated by Django 4.2 on 2023-04-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0010_alter_petshopapp_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petshopapp',
            old_name='nome',
            new_name='nome_do_tutor',
        ),
    ]
