# Generated by Django 4.2 on 2023-04-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0011_rename_nome_petshopapp_nome_do_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petshopapp',
            old_name='id_book',
            new_name='id_petshop',
        ),
    ]
