# Generated by Django 4.2 on 2023-04-22 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0012_rename_id_book_petshopapp_id_petshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='petshopapp',
            name='email',
            field=models.EmailField(default=uuid.uuid4, max_length=50),
        ),
    ]
