# Generated by Django 4.2 on 2023-04-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0014_procedimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Procedimento',
        ),
    ]
