# Generated by Django 4.2 on 2023-04-27 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0015_delete_procedimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_petshop', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_dono', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('nome_do_pet', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.EmailField(default=uuid.uuid4, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_petshop', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='petshopapp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='petshopapp',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='petshopapp',
            name='nome_do_pet',
        ),
        migrations.RemoveField(
            model_name='petshopapp',
            name='nome_do_tutor',
        ),
        migrations.RemoveField(
            model_name='petshopapp',
            name='telefone',
        ),
    ]
