# Generated by Django 4.2 on 2023-05-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0018_delete_petshopapp_alter_servicos_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='preco',
            field=models.CharField(max_length=50),
        ),
    ]
